### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MrLivixx** [vladciphersky/donate-page#1]
Если прислали донат с большим текстом то страничка ломается. Если как-то возможно исправить, жду фикса
![image](https://user-images.githubusercontent.com/54632865/85330238-a60e9600-b4dc-11ea-984f-f8c3869caf1a.png)

**Comment by vladciphersky** [comment]
Это не баг. Таблица просто сжимается при большом тексте, это возможности Bootstrap. Если хочешь чтобы такого не было, выставляй в настройках DonationAlerts меньше макс. символов (допустим 50-70). С прошедшим^^
